[package]
name = "test_wasm_integrity_zome"
version = "0.0.1"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
edition = "2021"

[lib]
name = "test_wasm_integrity_zome"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1.0"
idk = { path = "../../../../idk" }
holochain_mock_idk = { path = "../../../../mock_idk", optional = true }

[features]
default = []
mock = ["holochain_mock_idk"]