[package]
name = "test_wasm_ser_regression"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com", "freesig" ]
edition = "2021"

[lib]
name = "test_wasm_ser_regression"
crate-type = [ "cdylib", "rlib" ]

[[example]]
name = "integrity_test_wasm_ser_regression"
path = "src/integrity.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
derive_more = "0.99.11"
serde = "1.0"
hdk = { path = "../../../../hdk" }
holochain_deterministic_integrity = { path = "../../../../holochain_deterministic_integrity" }

[features]
default = []
mock = ["hdk/mock"]
