[package]
name = "holochain_mock_idk"
version = "0.0.1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2021"
description = "A mock version of the holochain idk"
license = "Apache-2.0"
documentation = "https://docs.rs/holochain_mock_idk"

[dependencies]
idk = { path = "../../idk" }
mockall = { version = "0.11.0" }
