[package]
name = "test_wasm_create_entry"
version = "0.0.1"
authors = ["thedavidmeister", "thedavidmeister@gmail.com"]
edition = "2021"

[lib]
name = "test_wasm_create_entry"
crate-type = ["cdylib", "rlib"]

[[example]]
name = "integrity_test_wasm_create_entry"
path = "src/integrity.rs" 
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1.0"
holochain_test_wasm_common = { path = "../../../wasm_common", optional = true }
hdk = { path = "../../../../hdk", optional = true }
holochain_deterministic_integrity = { path = "../../../../holochain_deterministic_integrity" }

[features]
default = ["holochain_test_wasm_common", "hdk"]
integrity = []
mock = ["hdk/mock", "default"]
