[package]
name = "test_wasm_genesis_self_check_valid"
version = "0.0.1"
authors = ["thedavidmeister", "thedavidmeister@gmail.com"]
edition = "2021"

[lib]
name = "test_wasm_genesis_self_check_valid"
crate-type = ["cdylib", "rlib"]

[[example]]
name = "integrity_test_wasm_genesis_self_check_valid"
path = "src/integrity.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1.0"
hdk = { path = "../../../../hdk" }
holochain_deterministic_integrity = { path = "../../../../holochain_deterministic_integrity" }

[features]
default = []
mock = ["hdk/mock"]
