[package]
name = "kitsune_dht_arc"
version = "0.0.1"
authors = ["Michael Dougherty <maackle.d@gmail.com>"]
edition = "2018"

[dependencies]
derive_more = "0.99"
intervallum = "=1.3.0"
gcollections = "1.4.0"
serde = {version = "1.0", features = ["derive"]}

[features]
test_utils = []
