name: autoupdate

on:
    # Run on every push on every branch
    push:
    # Run when pull requests get labeled
    pull_request:
        types: [labeled, opened, ready_for_review, reopened]
        branches:
            - "develop"

jobs:
    autoupdate:
        name: autoupdate
        runs-on: ubuntu-latest
        steps:
            - uses: docker://chinthakagodawita/autoupdate-action:v1
              env:
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                  PR_FILTER: "labelled"
                  PR_LABELS: "autoupdate:opt-in"
                  MERGE_CONFLICT_ACTION: "fail"
                  MERGE_MSG: "Branch was auto-updated."
