name: detect critical check failures

on:
  status: {}

jobs:
  investigate_event:
    runs-on: ubuntu-latest
    if: >-
      github.event.state == 'error' ||
      github.event.state == 'failure'
    steps:
      - name: Debug
        env:
          STATE: ${{ github.event.state }}
          DESCRIPTION: ${{ github.event.description }}
        run: |
          echo "$STATE": "$DESCRIPTION"
          jq < ${GITHUB_EVENT_PATH}

          # gh pr list --base develop --head pr_debug_checks --json id,title,labels,url,statusCheckRollup
